#!/usr/bin/env bash
# The ecomono register is written in four places: claude/output-styles/ecomono.md,
# agent-skills/ecomono/SKILL.md, and the `gentle-ai:persona` blocks in both
# claude/CLAUDE.md and opencode/AGENTS.md. The two persona blocks are supposed to
# say the same thing to two different agents, and nothing keeps them saying it.
#
# They already diverged once, silently: opencode/AGENTS.md was missing the whole
# "default cold / deep-dive on request" rule, so the register's own default did
# not exist on that agent. Nobody noticed because a missing rule reads exactly
# like a rule being followed.
#
# This compares the two blocks as sets of lines and fails on any difference not
# listed below as deliberate. Order-independent on purpose: the blocks are
# rewritten by `gentle-ai sync`, and a reordering is not drift.
#
# ecomono: a set comparison, not a merge. Single-sourcing these is not available
# — the persona is generated by the gentle-ai binary, which has no source file in
# this repo. Upgrade path if gentle-ai ever exposes one: generate both from it and
# delete this script.

set -uo pipefail
cd "$(dirname "$0")"

block() { awk '/gentle-ai:persona/,/\/gentle-ai:persona/' "$1" | grep -v '^[[:space:]]*$' | sort; }

# Differences that are correct. opencode has no `Skill` tool, so its skill-loading
# section names a read mechanism instead, and it is worded tighter throughout.
expected_only_in_agents() {
  cat <<'EOF'
- Zero filler/hedging/cortesías: no "dale con gusto", "básicamente", "creo que quizás", "me parece que".
**Self-check BEFORE every response**: match request against `<available_skills>`? Yes → read SKILL.md via read mechanism BEFORE replying. Blocking requirement, not optional. Skipping = discipline failure.
Multiple skills can apply. Match by file context (extensions/paths) + task context (user intent).
`<available_skills>` in system prompt = authoritative list of installed skills.
EOF
}

expected_only_in_claude() {
  cat <<'EOF'
- Zero filler/hedging/cortesías: no "dale con gusto", "básicamente", "creo que quizás".
Multiple skills can apply at once. Match by file context (extensions, paths) and task context (what the user is asking for).
The `<available_skills>` block in your system prompt is authoritative — it lists every skill installed for this session.
**Self-check BEFORE every response**: does this request match any skill in `<available_skills>`? If yes, invoke it via the built-in `Skill` tool BEFORE generating your reply. This is a blocking requirement, not optional context. Skipping it is a discipline failure.
EOF
}

fail=0
report() { # report <label> <actual> <expected>
  local unexpected
  unexpected=$(comm -23 <(printf '%s\n' "$2" | grep -v '^$' | sort) <(printf '%s\n' "$3" | grep -v '^$' | sort))
  if [ -n "$unexpected" ]; then
    echo "DRIFT — only in $1, not listed as deliberate:"
    printf '  %s\n' "$unexpected"
    fail=1
  fi
  local vanished
  vanished=$(comm -13 <(printf '%s\n' "$2" | grep -v '^$' | sort) <(printf '%s\n' "$3" | grep -v '^$' | sort))
  if [ -n "$vanished" ]; then
    echo "STALE — listed as a deliberate difference in $1 but no longer present:"
    printf '  %s\n' "$vanished"
    fail=1
  fi
}

only_agents=$(comm -13 <(block claude/CLAUDE.md) <(block opencode/AGENTS.md))
only_claude=$(comm -23 <(block claude/CLAUDE.md) <(block opencode/AGENTS.md))

report "opencode/AGENTS.md" "$only_agents" "$(expected_only_in_agents)"
report "claude/CLAUDE.md"   "$only_claude" "$(expected_only_in_claude)"

[ $fail -eq 0 ] && echo "ok   persona blocks agree (4 deliberate differences, all accounted for)"
exit $fail
